= Writing doc like code
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
// Settings
:idprefix:
:idseparator: -

"*Docs-as-code*" refers to the process of writing documentation using the same tools that programmers use to manage source code.

By applying software development processes and tools to technical documentation, writers can more easily manage files and versions of publications or websites.

* Instead of writing statements in a programming language, writers compose text in a *lightweight markup language* such as AsciiDoc, Markdown, or reStructuredText. Content is saved in plain text files.

* Content is stored in a *version control system*, such as Git or Bitbucket.

* Writers use an *issue tracker* such as JIRA, to manage tasks and projects.

* Websites are built using a *static site generator*, such as Antora, Jekyll, or Hugo. The site generator uses a template to control the appearance and layout of the website. Content is separated from presentation, thereby keepoing documentation consistent across products and teams.

.Related topics

* https://gdstechnology.blog.gov.uk/2017/08/25/why-we-use-a-docs-as-code-approach-for-technical-documentation/[Why we use a ‘docs as code’ approach for technical documentation]


* http://www.writethedocs.org/guide/docs-as-code/



* https://idratherbewriting.com/2017/11/21/switching-to-docs-as-code/

* https://idratherbewriting.com/2018/07/03/docs-as-code-after-three-years/

* https://idratherbewriting.com/2017/06/02/when-docs-are-not-like-code/
