= Using iframes in AsciiDoc
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
// Settings
:idprefix:
:idseparator: -

You can display an external web page within an AsciiDoc file, by placing an HTML iframe element with CSS to make the iframe responsive, in a pass through block. For example: +
 +
// Source for this technique: https://benmarshall.me/responsive-iframes/
// https://neveruntilnow.com/antora/jamstack/latest/multimedia/multimedia-example.html
// https://neveruntilnow.com/kit/index.html
// https://neveruntilnow.com/docsite/markup/index.html
++++
<!-- HTML to embed an iframe -->
<div class="iframe-container">
  <iframe src="https://www.usps.com/" frameborder="0"></iframe>
</div>

<!-- CSS to make the iframe responsive -->
<style>
.iframe-container {
overflow: hidden;
padding-top: 100%;
position: relative;
}
.iframe-container iframe {
 border: 0;
 height: 100%;
 left: 0;
 position: absolute;
 top: 0;
 width: 100%;
}
</style>
++++

== Try it yourself

To try this technique, copy the code below into an AsciiDoc file. Then insert your choice of URL. This technique was adapted from https://benmarshall.me/responsive-iframes/.

[source, html]
----
++++
<!-- HTML to embed an iframe -->
<div class="iframe-container">
  <iframe src="#https://www.somedomain.com/path/filename.html#" frameborder="0"></iframe>
</div>

<!-- CSS to make the iframe responsive -->
<style>
.iframe-container {
overflow: hidden;
padding-top: 100%;
position: relative;
}
.iframe-container iframe {
 border: 0;
 height: 100%;
 left: 0;
 position: absolute;
 top: 0;
 width: 100%;
}
</style>
++++
----

[NOTE]
====
Some websites do not allow their pages to be displayed inside an iframe. If you see a message saying that the connection was refused, you cannot use that address in an iframe. The following URLs should work for demo purposes:

* https://neveruntilnow.com/antora/jamstack/latest/multimedia/multimedia-example.html +

* https://www.usps.com/
====
